config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'

  get 'auth/login', to: 'auth#login'
  get 'auth/log_out', to: 'auth#log_out'
  get 'auth(/:id)', to: 'auth#auth', as: 'auth'

  resources :invoices, only: [:index, :new, :create, :show] do
    get :send_email, on: :member
    resource :download, only: [:show], :controller => "invoices/downloads"
  end

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :invoice_emails
  accepts_nested_attributes_for :invoice_emails
  belongs_to :user
end

app/models/invoice_email.rb
class InvoiceEmail < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :email, email: true, uniqueness: true
  before_create :setup_activation
  has_many :invoices

  def external?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :require_login, only: %i[ log_out ]

  def login
  end

  def auth
    if @user = User.load_from_activation_token(params[:id])
      auto_login @user
      flash.keep[:notice] = "User Logged."
      respond_to do |format|
        format.html { redirect_to :controller => :invoices, :action => :index }
        # format.json { render :show, status: :created, location: @invoice }
      end
    else
      not_authenticated
    end
  end

  def log_out
    logout
    flash.keep[:notice] = "You have logout =("

    respond_to do |format|
      format.html { redirect_to root_path }
      # format.json { render :show, status: :created, location: @user }
    end
  end
end

app/controllers/invoices/downloads_controller.rb
class Invoices::DownloadsController < ApplicationController
  before_action :require_login
  before_action :set_invoice
  include InvoicesHelper

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: InvoicesHelper.invoice_filename(@invoice), template: 'invoices/pdf.html.erb',
               layout: 'invoice_pdf', locals: { invoice: @invoice }
      end
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:invoice_id])
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :require_login
  before_action :set_invoice, only: %i[ show edit update destroy send_email ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all.includes(:invoice_emails)
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.invoice_emails.build
  end

  # GET /invoices/1/send_email
  def send_email
    SendInvoiceEmailService.call(@invoice)
    respond_to do |format|
      format.html { redirect_to request.referer, notice: "Invoice was sent by email." }
      format.json { render :show, status: :created, location: @invoice }
    end
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user_id = current_user.id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.includes(:invoice_emails).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:number, :date, :company, :billed_to, :total_value, invoice_emails_attributes:[:email])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash.keep[:notice] = "Check your email to activate account."
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def self.invoice_filename(invoice)
    "Invoice #{invoice.id}.pdf"
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :billed_to %>
    <%= form.text_field :billed_to %>
  </div>

  <div class="field">
    <%= form.label :total_value %>
    <%= form.text_field :total_value %>
  </div>

  <%= form.fields_for :invoice_emails do |form_ie| %>
    <div id="fieldsetContainer">
      <fieldset id="0">
        <%= form.label :email %>
        <%= form_ie.email_field :email %>
      </fieldset>
    </div>
  <% end %>

  <!--div class="field">
    <%#= form.label :emails %>
    <%#= form.text_field :emails %>
  </div-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<p><button id="addInvoiceEmail">Add more emails</button></p>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert">Only the first email is displayed here</p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th>Company</th>
      <th>Billed to</th>
      <th>Total value</th>      
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.number %></td>
        <td><%= invoice.date %></td>
        <td><%= invoice.company %></td>
        <td><%= invoice.billed_to %></td>
        <td><%= invoice.total_value %></td>
        <td><%= invoice.invoice_emails.first.email %> </td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Send invoice by email', send_email_invoice_path(invoice) %></td>
        <td>
          <%= link_to "Download PDF", invoice_download_path(invoice, format: "pdf"),
                      target: "_blank", class: "download" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Invoice', new_invoice_path %></p>
<p><%= link_to 'Logout', auth_log_out_path %></p>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/pdf.html.erb
<div class="invoice">
  <h1>Invoice</h1>
 
  <h3>Billed to: <%= @invoice.billed_to %></h3>
  <h3>Date: <%= @invoice.date.strftime("%d, %B %Y") %></h3>
 
  <p><strong>Number: </strong><%= @invoice.number %></p>
  <p><strong>Company: </strong><%= @invoice.company %></p>
  <p>
    <strong>Emails: </strong>
    <% @invoice.invoice_emails.each do |invoice_email| %>
      <%= invoice_email.email %>
    <% end %>
  </p>
  
  <p>
    <h2>
      <td style="text-align: right">Total: </td>
      <td> <%= @invoice.total_value %> </td>
    </h2>
  </p>
</div>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'Edit', edit_invoice_path(@invoice) %> 

<div class="invoice">
  <h1>Invoice</h1>
 
  <h3>Billed to: <%= @invoice.billed_to %></h3>
  <h3>Date: <%= @invoice.date.strftime("%B %d, %Y") %></h3>
 
  <table>
    <thead>
        <tr>
          <th>Number</th>
          <th>Company</th>
          <% @invoice.invoice_emails.each do |invoice_email| %>
            <th>Email</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @invoice.number %></td>
          <td><%= @invoice.company %></td>
          <% @invoice.invoice_emails.each do |invoice_email| %>
            <td> <%= invoice_email.email %> </td>
          <% end %>
        </tr>
        <tr class="total">
          <td style="text-align: right">Total: </td>
          <td><%= @invoice.total_value %></span></td>
        </tr>
      </tbody>
  </table>
 
  <!--div class="notes">
    <p><strong>Date:</strong> <%= @invoice.date %></p>
  </div-->
</div>

<p><%= link_to "Download PDF",
  invoice_download_path(@invoice, format: "pdf"),
  target: "_blank",
  class: "download" %></p>

<p><%= link_to 'Send invoice by email', send_email_invoice_path(@invoice) %></p>

<p><%= link_to 'Back', invoices_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyChallengeHusky</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/invoice_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invoices</title>
  <style>
    <%= Rails.application.assets.find_asset('invoices.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1> Generate Token </h1>

<%= form_with model:@user do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label :email, "Email" %>
  <%= form.email_field :email %>
  <%= form.submit "Create user" %>
<% end %>

<p> 
  <%= link_to 'Back', root_path %> 
</p>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Husky Code Challenge</h1>

<p><%= link_to 'Generate token', new_user_path %></p>
<p><%= link_to 'Login', auth_login_path %></p>